#!/usr/bin/env node
var arguments = process.argv,
    problemNumber = arguments[2],
    problemManager = require("./ProblemManager");

if(problemNumber==="tests") {
    require("./Tests").runAllTests();
    return;
}

if(problemNumber && problemNumber>0)
    problemManager.runProblem(problemNumber);
else
    console.log("Please specify a problem to run.");
